package in.lubetk.allowance.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Buckets")
public class Bucket
{
	public String bucketId;
	public String name;
	public int currentTotal;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getBucketId()
	{
		return bucketId;
	}
	public void setBucketId(String bucketId)
	{
		this.bucketId = bucketId;
	}
	
	public String getName()
	{
		return name;
	}
	public void setName(String name)
	{
		this.name = name;
	}
	
	public int getCurrentTotal()
	{
		return currentTotal;
	}
	public void setCurrentTotal(int currentTotal)
	{
		this.currentTotal = currentTotal;
	}
}
