package in.lubetk.allowance.db;

import java.util.HashSet;
import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Kids")
public class Kid
{
	private String kidId;
	private String emailAddress;
	private String name;
	private int allowance;
	private Set<String> buckets;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getKidId()
	{
		return kidId;
	}
	public void setKidId(String kidId)
	{
		this.kidId = kidId;
	}
	
	public String getEmailAddress()
	{
		return emailAddress;
	}
	public void setEmailAddress(String emailAddress)
	{
		this.emailAddress = emailAddress;
	}
	
	public String getName()
	{
		return name;
	}
	public void setName(String name)
	{
		this.name = name;
	}
	
	public int getAllowance()
	{
		return allowance;
	}
	public void setAllowance(int allowance)
	{
		this.allowance = allowance;
	}
	
	public Set<String> getBuckets()
	{
		return buckets;
	}
	public void setBuckets(Set<String> buckets)
	{
		this.buckets = buckets;
	}
	public void addBucket(String bucketId, int allocation)
	{
		if (buckets == null)
			buckets = new HashSet<String>();
		buckets.add(bucketId + "#" + allocation);
	}
}
