package in.lubetk.allowance.db;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Kids")
public class Kid
{
	public String kidId;
	public String emailAddress;
	public String name;
	public int allowance;
	public Set<String> buckets;
	public Set<Integer> allocations;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getKidId()
	{
		return kidId;
	}
	public void setKidId(String kidId)
	{
		this.kidId = kidId;
	}
	
	public String getEmailAddress()
	{
		return emailAddress;
	}
	public void setEmailAddress(String emailAddress)
	{
		this.emailAddress = emailAddress;
	}
	
	public String getName()
	{
		return name;
	}
	public void setName(String name)
	{
		this.name = name;
	}
	
	public int getAllowance()
	{
		return allowance;
	}
	public void setAllowance(int allowance)
	{
		this.allowance = allowance;
	}
	
	public Set<String> getBuckets()
	{
		return buckets;
	}
	public void setBuckets(Set<String> buckets)
	{
		this.buckets = buckets;
	}
}
