package in.lubetk.allowance.db;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Parents")
public class Parent
{
	String parentId;
	String name;
	String emailAddress;
	String password;
	String familyId;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getParentId()
	{
		return parentId;
	}
	public void setParentId(String parentId)
	{
		this.parentId = parentId;
	}
	
	public String getName()
	{
		return name;
	}
	public void setName(String name)
	{
		this.name = name;
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "ParentEmail")
	public String getEmailAddress()
	{
		return emailAddress;
	}
	public void setEmailAddress(String emailAddress)
	{
		this.emailAddress = emailAddress;
	}
	
	public String getPassword()
	{
		return password;
	}
	public void setPassword(String password)
	{
		this.password = password;
	}
	
	public String getFamilyId()
	{
		return familyId;
	}
	public void setFamilyId(String familyId)
	{
		this.familyId = familyId;
	}
}
